package gumps

// StandardGUMP provides a set of layout methods built on top of BaseGUMP's
// layout methods that make it a little more convenient to build GUMPs with the
// standard theme.
//
// STANDARD THEME:
// Background...........................
// Text Hue.............................
// Label Button.........................
// Checkbox Button......................
// Radio Button.........................
type StandardGUMP struct {
	BaseGUMP
}
